package com.odss.seu.mapper;

import com.odss.seu.vo.DishType;
import com.odss.seu.vo.DishTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    long countByExample(DishTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int deleteByExample(DishTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int insert(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int insertSelective(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    List<DishType> selectByExample(DishTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    DishType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") DishType record, @Param("example") DishTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByExample(@Param("record") DishType record, @Param("example") DishTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByPrimaryKeySelective(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dishtype
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByPrimaryKey(DishType record);
}