package com.odss.seu.mapper;

import com.odss.seu.vo.Dish;
import com.odss.seu.vo.DishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    long countByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int deleteByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int insertSelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    List<Dish> selectByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    Dish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByExample(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByPrimaryKeySelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    int updateByPrimaryKey(Dish record);
}