package com.odss.seu.mapper;

import com.odss.seu.vo.Order;
import com.odss.seu.vo.OrderExample;
import java.util.List;

import com.odss.seu.vo.Statistics;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     * @param example
     */
    List<Statistics> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_order
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    int updateByPrimaryKey(Order record);

    List<Order> queryForList();
}