package com.odss.seu.vo;

import com.fasterxml.jackson.annotation.JsonView;

import java.io.Serializable;

public class Dish implements Serializable {
    private static final long serialVersionUID =1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Description
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.SummaryWithDetail.class)
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Picture
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Price
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private DishType type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_dish.Recommend
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.SummaryWithDetail.class)
    private Integer recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.ID
     *
     * @return the value of ods_dish.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.ID
     *
     * @param id the value for ods_dish.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Name
     *
     * @return the value of ods_dish.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Name
     *
     * @param name the value for ods_dish.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Description
     *
     * @return the value of ods_dish.Description
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Description
     *
     * @param description the value for ods_dish.Description
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Picture
     *
     * @return the value of ods_dish.Picture
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Picture
     *
     * @param picture the value for ods_dish.Picture
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Price
     *
     * @return the value of ods_dish.Price
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Price
     *
     * @param price the value for ods_dish.Price
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Type
     *
     * @return the value of ods_dish.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public DishType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Type
     *
     * @param type the value for ods_dish.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setType(DishType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_dish.Recommend
     *
     * @return the value of ods_dish.Recommend
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_dish.Recommend
     *
     * @param recommend the value for ods_dish.Recommend
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }
}