package com.odss.seu.vo;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_orderinfo.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_orderinfo.Order
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_orderinfo.Dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer dish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_orderinfo.DishState
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer dishstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_orderinfo.ID
     *
     * @return the value of ods_orderinfo.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_orderinfo.ID
     *
     * @param id the value for ods_orderinfo.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_orderinfo.Order
     *
     * @return the value of ods_orderinfo.Order
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_orderinfo.Order
     *
     * @param order the value for ods_orderinfo.Order
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_orderinfo.Dish
     *
     * @return the value of ods_orderinfo.Dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getDish() {
        return dish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_orderinfo.Dish
     *
     * @param dish the value for ods_orderinfo.Dish
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setDish(Integer dish) {
        this.dish = dish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_orderinfo.DishState
     *
     * @return the value of ods_orderinfo.DishState
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getDishstate() {
        return dishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_orderinfo.DishState
     *
     * @param dishstate the value for ods_orderinfo.DishState
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setDishstate(Integer dishstate) {
        this.dishstate = dishstate;
    }
}