package com.odss.seu.vo;

import java.util.ArrayList;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("`Order` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("`Order` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Integer value) {
            addCriterion("`Order` =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("`Order` <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("`Order` >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("`Order` >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("`Order` <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("`Order` <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("`Order` in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("`Order` not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("`Order` between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("`Order` not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andDishIsNull() {
            addCriterion("Dish is null");
            return (Criteria) this;
        }

        public Criteria andDishIsNotNull() {
            addCriterion("Dish is not null");
            return (Criteria) this;
        }

        public Criteria andDishEqualTo(Integer value) {
            addCriterion("Dish =", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishNotEqualTo(Integer value) {
            addCriterion("Dish <>", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishGreaterThan(Integer value) {
            addCriterion("Dish >", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dish >=", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishLessThan(Integer value) {
            addCriterion("Dish <", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishLessThanOrEqualTo(Integer value) {
            addCriterion("Dish <=", value, "dish");
            return (Criteria) this;
        }

        public Criteria andDishIn(List<Integer> values) {
            addCriterion("Dish in", values, "dish");
            return (Criteria) this;
        }

        public Criteria andDishNotIn(List<Integer> values) {
            addCriterion("Dish not in", values, "dish");
            return (Criteria) this;
        }

        public Criteria andDishBetween(Integer value1, Integer value2) {
            addCriterion("Dish between", value1, value2, "dish");
            return (Criteria) this;
        }

        public Criteria andDishNotBetween(Integer value1, Integer value2) {
            addCriterion("Dish not between", value1, value2, "dish");
            return (Criteria) this;
        }

        public Criteria andDishstateIsNull() {
            addCriterion("DishState is null");
            return (Criteria) this;
        }

        public Criteria andDishstateIsNotNull() {
            addCriterion("DishState is not null");
            return (Criteria) this;
        }

        public Criteria andDishstateEqualTo(Integer value) {
            addCriterion("DishState =", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateNotEqualTo(Integer value) {
            addCriterion("DishState <>", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateGreaterThan(Integer value) {
            addCriterion("DishState >", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("DishState >=", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateLessThan(Integer value) {
            addCriterion("DishState <", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateLessThanOrEqualTo(Integer value) {
            addCriterion("DishState <=", value, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateIn(List<Integer> values) {
            addCriterion("DishState in", values, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateNotIn(List<Integer> values) {
            addCriterion("DishState not in", values, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateBetween(Integer value1, Integer value2) {
            addCriterion("DishState between", value1, value2, "dishstate");
            return (Criteria) this;
        }

        public Criteria andDishstateNotBetween(Integer value1, Integer value2) {
            addCriterion("DishState not between", value1, value2, "dishstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_orderinfo
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 08 14:07:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_orderinfo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}