package com.odss.seu.vo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.Table
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.Time
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.DishQuality
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer dishquality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.CookSpeed
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer cookspeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_order.ServeAttitude
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer serveattitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.ID
     *
     * @return the value of ods_order.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.ID
     *
     * @param id the value for ods_order.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.Table
     *
     * @return the value of ods_order.Table
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.Table
     *
     * @param table the value for ods_order.Table
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setTable(Integer table) {
        this.table = table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.Time
     *
     * @return the value of ods_order.Time
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.Time
     *
     * @param time the value for ods_order.Time
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.State
     *
     * @return the value of ods_order.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.State
     *
     * @param state the value for ods_order.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.DishQuality
     *
     * @return the value of ods_order.DishQuality
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getDishquality() {
        return dishquality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.DishQuality
     *
     * @param dishquality the value for ods_order.DishQuality
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setDishquality(Integer dishquality) {
        this.dishquality = dishquality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.CookSpeed
     *
     * @return the value of ods_order.CookSpeed
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getCookspeed() {
        return cookspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.CookSpeed
     *
     * @param cookspeed the value for ods_order.CookSpeed
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setCookspeed(Integer cookspeed) {
        this.cookspeed = cookspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_order.ServeAttitude
     *
     * @return the value of ods_order.ServeAttitude
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getServeattitude() {
        return serveattitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_order.ServeAttitude
     *
     * @param serveattitude the value for ods_order.ServeAttitude
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setServeattitude(Integer serveattitude) {
        this.serveattitude = serveattitude;
    }
}