package com.odss.seu.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public StatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
//_________________________________________________________________________________________________________________________
        public Criteria andstartTimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andstartTimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andstartTimeEqualTo(Integer value) {
            addCriterion("startTime =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeNotEqualTo(Integer value) {
            addCriterion("startTime <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeGreaterThan(Integer value) {
            addCriterion("startTime >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("startTime >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeLessThan(Integer value) {
            addCriterion("startTime <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeLessThanOrEqualTo(Integer value) {
            addCriterion("startTime <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeIn(List<Integer> values) {
            addCriterion("startTime in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeNotIn(List<Integer> values) {
            addCriterion("startTime not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeBetween(Integer value1, Integer value2) {
            addCriterion("startTime between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andstartTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("stratTime not between", value1, value2, "startTime");
            return (Criteria) this;
        }
//
        public Criteria andendTimeIsNull() {
            addCriterion("`endTime` is null");
            return (Criteria) this;
        }

        public Criteria andendTimeIsNotNull() {
            addCriterion("`endTime` is not null");
            return (Criteria) this;
        }

        public Criteria andendTimeEqualTo(String value) {
            addCriterion("`endTime` =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeNotEqualTo(String value) {
            addCriterion("`endTime` <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeGreaterThan(String value) {
            addCriterion("`endTime` >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeGreaterThanOrEqualTo(String value) {
            addCriterion("`endTime` >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeLessThan(String value) {
            addCriterion("`endTime` <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeLessThanOrEqualTo(Date value) {
            addCriterion("`endTime` <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeLike(String value) {
            addCriterion("`endTime` like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeNotLike(String value) {
            addCriterion("`endTime` not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeIn(List<String> values) {
            addCriterion("`endTime` in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeNotIn(List<String> values) {
            addCriterion("`endTime` not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeBetween(String value1, String value2) {
            addCriterion("`endTime` between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andendTimeNotBetween(String value1, String value2) {
            addCriterion("`endTime` not between", value1, value2, "endTime");
            return (Criteria) this;
        }
//
        public Criteria andincomeIsNull() {
            addCriterion("income is null");
            return (Criteria) this;
        }

        public Criteria andincomeIsNotNull() {
            addCriterion("income is not null");
            return (Criteria) this;
        }

        public Criteria andincomeEqualTo(String value) {
            addCriterion("income =", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeNotEqualTo(String value) {
            addCriterion("income <>", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeGreaterThan(String value) {
            addCriterion("income >", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeGreaterThanOrEqualTo(String value) {
            addCriterion("income >=", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeLessThan(String value) {
            addCriterion("income <", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeLessThanOrEqualTo(String value) {
            addCriterion("income <=", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeLike(String value) {
            addCriterion("income like", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeNotLike(String value) {
            addCriterion("income not like", value, "income");
            return (Criteria) this;
        }

        public Criteria andincomeIn(List<String> values) {
            addCriterion("income in", values, "income");
            return (Criteria) this;
        }

        public Criteria andincomeNotIn(List<String> values) {
            addCriterion("income not in", values, "income");
            return (Criteria) this;
        }

        public Criteria andincomeBetween(String value1, String value2) {
            addCriterion("income between", value1, value2, "income");
            return (Criteria) this;
        }

        public Criteria andincomeNotBetween(String value1, String value2) {
            addCriterion("income not between", value1, value2, "income");
            return (Criteria) this;
        }
//
        public Criteria andsellNumIsNull() {
            addCriterion("sellNum is null");
            return (Criteria) this;
        }

        public Criteria andsellNumIsNotNull() {
            addCriterion("sellNum is not null");
            return (Criteria) this;
        }

        public Criteria andsellNumEqualTo(String value) {
            addCriterion("sellNum =", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumNotEqualTo(String value) {
            addCriterion("sellNum <>", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumGreaterThan(String value) {
            addCriterion("sellNum >", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumGreaterThanOrEqualTo(String value) {
            addCriterion("sellNum >=", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumLessThan(String value) {
            addCriterion("sellNum <", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumLessThanOrEqualTo(String value) {
            addCriterion("sellNum <=", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumLike(String value) {
            addCriterion("sellNum like", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumNotLike(String value) {
            addCriterion("sellNum not like", value, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumIn(List<String> values) {
            addCriterion("sellNum in", values, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumNotIn(List<String> values) {
            addCriterion("sellNum not in", values, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumBetween(String value1, String value2) {
            addCriterion("sellNum between", value1, value2, "sellNum");
            return (Criteria) this;
        }

        public Criteria andsellNumNotBetween(String value1, String value2) {
            addCriterion("sellNum not between", value1, value2, "sellNum");
            return (Criteria) this;
        }
//
        public Criteria andfantaiIsNull() {
            addCriterion("fantai is null");
            return (Criteria) this;
        }

        public Criteria andfantaiIsNotNull() {
            addCriterion("fantai is not null");
            return (Criteria) this;
        }

        public Criteria andfantaiEqualTo(String value) {
            addCriterion("fantai =", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiNotEqualTo(String value) {
            addCriterion("fantai <>", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiGreaterThan(String value) {
            addCriterion("fantai >", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiGreaterThanOrEqualTo(String value) {
            addCriterion("fantai >=", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiLessThan(String value) {
            addCriterion("fantai <", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiLessThanOrEqualTo(String value) {
            addCriterion("fantai <=", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiLike(String value) {
            addCriterion("fantai like", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiNotLike(String value) {
            addCriterion("fantai not like", value, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiIn(List<String> values) {
            addCriterion("fantai in", values, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiNotIn(List<String> values) {
            addCriterion("fantai not in", values, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiBetween(String value1, String value2) {
            addCriterion("fantai between", value1, value2, "fantai");
            return (Criteria) this;
        }

        public Criteria andfantaiNotBetween(String value1, String value2) {
            addCriterion("fantai not between", value1, value2, "fantai");
            return (Criteria) this;
        }

    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 08 14:07:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ods_user
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    protected String orderByClause;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    protected boolean distinct;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    protected List<StatisticsExample.Criteria> oredCriteria;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public StatisticsExample() {
//        oredCriteria = new ArrayList<StatisticsExample.Criteria>();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public void setOrderByClause(String orderByClause) {
//        this.orderByClause = orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public String getOrderByClause() {
//        return orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public void setDistinct(boolean distinct) {
//        this.distinct = distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public boolean isDistinct() {
//        return distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public List<StatisticsExample.Criteria> getOredCriteria() {
//        return oredCriteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public void or(StatisticsExample.Criteria criteria) {
//        oredCriteria.add(criteria);
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public StatisticsExample.Criteria or() {
//        StatisticsExample.Criteria criteria = createCriteriaInternal();
//        oredCriteria.add(criteria);
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public StatisticsExample.Criteria createCriteria() {
//       StatisticsExample.Criteria criteria = createCriteriaInternal();
//        if (oredCriteria.size() == 0) {
//            oredCriteria.add(criteria);
//        }
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    protected StatisticsExample.Criteria createCriteriaInternal() {
//        StatisticsExample.Criteria criteria = new StatisticsExample.Criteria();
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public void clear() {
//        oredCriteria.clear();
//        orderByClause = null;
//        distinct = false;
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    protected abstract static class GeneratedCriteria {
//        protected List<StatisticsExample.Criterion> criteria;
//
//        protected GeneratedCriteria() {
//            super();
//            criteria = new ArrayList<StatisticsExample.Criterion>();
//        }
//
//        public boolean isValid() {
//            return criteria.size() > 0;
//        }
//
//        public List<StatisticsExample.Criterion> getAllCriteria() {
//            return criteria;
//        }
//
//        public List<StatisticsExample.Criterion> getCriteria() {
//            return criteria;
//        }
//
//        protected void addCriterion(String condition) {
//            if (condition == null) {
//                throw new RuntimeException("Value for condition cannot be null");
//            }
//            criteria.add(new StatisticsExample.Criterion(condition));
//        }
//
//        protected void addCriterion(String condition, Object value, String property) {
//            if (value == null) {
//                throw new RuntimeException("Value for " + property + " cannot be null");
//            }
//            criteria.add(new StatisticsExample.Criterion(condition, value));
//        }
//
//        protected void addCriterion(String condition, Object value1, Object value2, String property) {
//            if (value1 == null || value2 == null) {
//                throw new RuntimeException("Between values for " + property + " cannot be null");
//            }
//            criteria.add(new StatisticsExample.Criterion(condition, value1, value2));
//        }
//
//        public StatisticsExample.Criteria andIdIsNull() {
//            addCriterion("ID is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdIsNotNull() {
//            addCriterion("ID is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdEqualTo(Integer value) {
//            addCriterion("ID =", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdNotEqualTo(Integer value) {
//            addCriterion("ID <>", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdGreaterThan(Integer value) {
//            addCriterion("ID >", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdGreaterThanOrEqualTo(Integer value) {
//            addCriterion("ID >=", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdLessThan(Integer value) {
//            addCriterion("ID <", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdLessThanOrEqualTo(Integer value) {
//            addCriterion("ID <=", value, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdIn(List<Integer> values) {
//            addCriterion("ID in", values, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdNotIn(List<Integer> values) {
//            addCriterion("ID not in", values, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdBetween(Integer value1, Integer value2) {
//            addCriterion("ID between", value1, value2, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andIdNotBetween(Integer value1, Integer value2) {
//            addCriterion("ID not between", value1, value2, "id");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameIsNull() {
//            addCriterion("`Name` is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameIsNotNull() {
//            addCriterion("`Name` is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameEqualTo(String value) {
//            addCriterion("`Name` =", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameNotEqualTo(String value) {
//            addCriterion("`Name` <>", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameGreaterThan(String value) {
//            addCriterion("`Name` >", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameGreaterThanOrEqualTo(String value) {
//            addCriterion("`Name` >=", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameLessThan(String value) {
//            addCriterion("`Name` <", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameLessThanOrEqualTo(String value) {
//            addCriterion("`Name` <=", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameLike(String value) {
//            addCriterion("`Name` like", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameNotLike(String value) {
//            addCriterion("`Name` not like", value, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameIn(List<String> values) {
//            addCriterion("`Name` in", values, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameNotIn(List<String> values) {
//            addCriterion("`Name` not in", values, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameBetween(String value1, String value2) {
//            addCriterion("`Name` between", value1, value2, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andNameNotBetween(String value1, String value2) {
//            addCriterion("`Name` not between", value1, value2, "name");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoIsNull() {
//            addCriterion("Photo is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoIsNotNull() {
//            addCriterion("Photo is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoEqualTo(String value) {
//            addCriterion("Photo =", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoNotEqualTo(String value) {
//            addCriterion("Photo <>", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoGreaterThan(String value) {
//            addCriterion("Photo >", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoGreaterThanOrEqualTo(String value) {
//            addCriterion("Photo >=", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoLessThan(String value) {
//            addCriterion("Photo <", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoLessThanOrEqualTo(String value) {
//            addCriterion("Photo <=", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoLike(String value) {
//            addCriterion("Photo like", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoNotLike(String value) {
//            addCriterion("Photo not like", value, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoIn(List<String> values) {
//            addCriterion("Photo in", values, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoNotIn(List<String> values) {
//            addCriterion("Photo not in", values, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoBetween(String value1, String value2) {
//            addCriterion("Photo between", value1, value2, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPhotoNotBetween(String value1, String value2) {
//            addCriterion("Photo not between", value1, value2, "photo");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountIsNull() {
//            addCriterion("Account is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountIsNotNull() {
//            addCriterion("Account is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountEqualTo(String value) {
//            addCriterion("Account =", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountNotEqualTo(String value) {
//            addCriterion("Account <>", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountGreaterThan(String value) {
//            addCriterion("Account >", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountGreaterThanOrEqualTo(String value) {
//            addCriterion("Account >=", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountLessThan(String value) {
//            addCriterion("Account <", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountLessThanOrEqualTo(String value) {
//            addCriterion("Account <=", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountLike(String value) {
//            addCriterion("Account like", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountNotLike(String value) {
//            addCriterion("Account not like", value, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountIn(List<String> values) {
//            addCriterion("Account in", values, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountNotIn(List<String> values) {
//            addCriterion("Account not in", values, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountBetween(String value1, String value2) {
//            addCriterion("Account between", value1, value2, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andAccountNotBetween(String value1, String value2) {
//            addCriterion("Account not between", value1, value2, "account");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordIsNull() {
//            addCriterion("Pasword is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordIsNotNull() {
//            addCriterion("Pasword is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordEqualTo(String value) {
//            addCriterion("Pasword =", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordNotEqualTo(String value) {
//            addCriterion("Pasword <>", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordGreaterThan(String value) {
//            addCriterion("Pasword >", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordGreaterThanOrEqualTo(String value) {
//            addCriterion("Pasword >=", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordLessThan(String value) {
//            addCriterion("Pasword <", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordLessThanOrEqualTo(String value) {
//            addCriterion("Pasword <=", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordLike(String value) {
//            addCriterion("Pasword like", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordNotLike(String value) {
//            addCriterion("Pasword not like", value, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordIn(List<String> values) {
//            addCriterion("Pasword in", values, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordNotIn(List<String> values) {
//            addCriterion("Pasword not in", values, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordBetween(String value1, String value2) {
//            addCriterion("Pasword between", value1, value2, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andPaswordNotBetween(String value1, String value2) {
//            addCriterion("Pasword not between", value1, value2, "pasword");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeIsNull() {
//            addCriterion("`Type` is null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeIsNotNull() {
//            addCriterion("`Type` is not null");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeEqualTo(Integer value) {
//            addCriterion("`Type` =", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeNotEqualTo(Integer value) {
//            addCriterion("`Type` <>", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeGreaterThan(Integer value) {
//            addCriterion("`Type` >", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeGreaterThanOrEqualTo(Integer value) {
//            addCriterion("`Type` >=", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeLessThan(Integer value) {
//            addCriterion("`Type` <", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeLessThanOrEqualTo(Integer value) {
//            addCriterion("`Type` <=", value, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeIn(List<Integer> values) {
//            addCriterion("`Type` in", values, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeNotIn(List<Integer> values) {
//            addCriterion("`Type` not in", values, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeBetween(Integer value1, Integer value2) {
//            addCriterion("`Type` between", value1, value2, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//
//        public StatisticsExample.Criteria andTypeNotBetween(Integer value1, Integer value2) {
//            addCriterion("`Type` not between", value1, value2, "type");
//            return (StatisticsExample.Criteria) this;
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table ods_user
//     *
//     * @mbg.generated do_not_delete_during_merge Fri Sep 08 14:07:18 CST 2017
//     */
//    public static class Criteria extends StatisticsExample.GeneratedCriteria {
//
//        protected Criteria() {
//            super();
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table ods_user
//     *
//     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
//     */
//    public static class Criterion {
//        private String condition;
//
//        private Object value;
//
//        private Object secondValue;
//
//        private boolean noValue;
//
//        private boolean singleValue;
//
//        private boolean betweenValue;
//
//        private boolean listValue;
//
//        private String typeHandler;
//
//        public String getCondition() {
//            return condition;
//        }
//
//        public Object getValue() {
//            return value;
//        }
//
//        public Object getSecondValue() {
//            return secondValue;
//        }
//
//        public boolean isNoValue() {
//            return noValue;
//        }
//
//        public boolean isSingleValue() {
//            return singleValue;
//        }
//
//        public boolean isBetweenValue() {
//            return betweenValue;
//        }
//
//        public boolean isListValue() {
//            return listValue;
//        }
//
//        public String getTypeHandler() {
//            return typeHandler;
//        }
//
//        protected Criterion(String condition) {
//            super();
//            this.condition = condition;
//            this.typeHandler = null;
//            this.noValue = true;
//        }
//
//        protected Criterion(String condition, Object value, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.typeHandler = typeHandler;
//            if (value instanceof List<?>) {
//                this.listValue = true;
//            } else {
//                this.singleValue = true;
//            }
//        }
//
//        protected Criterion(String condition, Object value) {
//            this(condition, value, null);
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.secondValue = secondValue;
//            this.typeHandler = typeHandler;
//            this.betweenValue = true;
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue) {
//            this(condition, value, secondValue, null);
//        }
//    }
//}
