package com.odss.seu.vo;

public class Table {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.PersonalNum
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer personalnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.ID
     *
     * @return the value of ods_table.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.ID
     *
     * @param id the value for ods_table.ID
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.PersonalNum
     *
     * @return the value of ods_table.PersonalNum
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getPersonalnum() {
        return personalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.PersonalNum
     *
     * @param personalnum the value for ods_table.PersonalNum
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setPersonalnum(Integer personalnum) {
        this.personalnum = personalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.State
     *
     * @return the value of ods_table.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.State
     *
     * @param state the value for ods_table.State
     *
     * @mbg.generated Thu Sep 07 08:52:02 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}