package com.odss.seu.vo;

import com.fasterxml.jackson.annotation.JsonView;

import java.io.Serializable;

public class Table implements Serializable{
    private static final long serialVersionUID =1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.PersonalNum
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer personalnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_table.State
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.ID
     *
     * @return the value of ods_table.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.ID
     *
     * @param id the value for ods_table.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.PersonalNum
     *
     * @return the value of ods_table.PersonalNum
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getPersonalnum() {
        return personalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.PersonalNum
     *
     * @param personalnum the value for ods_table.PersonalNum
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setPersonalnum(Integer personalnum) {
        this.personalnum = personalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_table.State
     *
     * @return the value of ods_table.State
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_table.State
     *
     * @param state the value for ods_table.State
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}