package com.odss.seu.vo;

import java.io.Serializable;

public class UserType implements Serializable {
    private static final long serialVersionUID =1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_usertype.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_usertype.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_usertype.ID
     *
     * @return the value of ods_usertype.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_usertype.ID
     *
     * @param id the value for ods_usertype.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_usertype.Name
     *
     * @return the value of ods_usertype.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_usertype.Name
     *
     * @param name the value for ods_usertype.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}