package com.odss.seu.vo;

import com.fasterxml.jackson.annotation.JsonView;

import java.io.Serializable;

public class User implements Serializable {
    private static final long serialVersionUID =1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.Photo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.SummaryWithDetail.class)
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.Account
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.Pasword
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.SummaryWithDetail.class)
    private String pasword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_user.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    @JsonView(ViewLevel.Summary.class)
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.ID
     *
     * @return the value of ods_user.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.ID
     *
     * @param id the value for ods_user.ID
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.Name
     *
     * @return the value of ods_user.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.Name
     *
     * @param name the value for ods_user.Name
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.Photo
     *
     * @return the value of ods_user.Photo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.Photo
     *
     * @param photo the value for ods_user.Photo
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.Account
     *
     * @return the value of ods_user.Account
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.Account
     *
     * @param account the value for ods_user.Account
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.Pasword
     *
     * @return the value of ods_user.Pasword
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public String getPasword() {
        return pasword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.Pasword
     *
     * @param pasword the value for ods_user.Pasword
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_user.Type
     *
     * @return the value of ods_user.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_user.Type
     *
     * @param type the value for ods_user.Type
     *
     * @mbg.generated Fri Sep 08 14:07:18 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}